server:
  servlet:
    context-path: /mall-user
  port: 8090

spring:
  application:
    name: mall-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.37.67:3306/lee-mall?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  mapper-locations: classpath:/mapper/*Mapper.xml